db:
  image: postgres:latest
  volumes_from:
    - data
  ports:
    - "5432:5432"
data:
  image: postgres:latest
  volumes:
    - /var/lib/postgresql
  command: "true"
elasticsearch:
  image: elasticsearch:1.7.3
web:
  build: .
  command: runserver 0.0.0.0:8000
  volumes:
    - .:/app/src
  links:
    - db:db
    - elasticsearch:elasticsearch
  ports:
    - "8000:8000"
